/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as MilitaresRouteImport } from './routes/militares'
import { Route as MeusResultadosRouteImport } from './routes/meus-resultados'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as IndexRouteImport } from './routes/index'

const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaresRoute = MilitaresRouteImport.update({
  id: '/militares',
  path: '/militares',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusResultadosRoute = MeusResultadosRouteImport.update({
  id: '/meus-resultados',
  path: '/meus-resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meus-resultados': typeof MeusResultadosRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meus-resultados': typeof MeusResultadosRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/auth': typeof AuthRoute
  '/importar': typeof ImportarRoute
  '/meus-resultados': typeof MeusResultadosRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovacoes'
    | '/auth'
    | '/importar'
    | '/meus-resultados'
    | '/militares'
    | '/registros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprovacoes'
    | '/auth'
    | '/importar'
    | '/meus-resultados'
    | '/militares'
    | '/registros'
  id:
    | '__root__'
    | '/'
    | '/aprovacoes'
    | '/auth'
    | '/importar'
    | '/meus-resultados'
    | '/militares'
    | '/registros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprovacoesRoute: typeof AprovacoesRoute
  AuthRoute: typeof AuthRoute
  ImportarRoute: typeof ImportarRoute
  MeusResultadosRoute: typeof MeusResultadosRoute
  MilitaresRoute: typeof MilitaresRoute
  RegistrosRoute: typeof RegistrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/militares': {
      id: '/militares'
      path: '/militares'
      fullPath: '/militares'
      preLoaderRoute: typeof MilitaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-resultados': {
      id: '/meus-resultados'
      path: '/meus-resultados'
      fullPath: '/meus-resultados'
      preLoaderRoute: typeof MeusResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprovacoesRoute: AprovacoesRoute,
  AuthRoute: AuthRoute,
  ImportarRoute: ImportarRoute,
  MeusResultadosRoute: MeusResultadosRoute,
  MilitaresRoute: MilitaresRoute,
  RegistrosRoute: RegistrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
