/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as MilitaresRouteImport } from './routes/militares'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaresRoute = MilitaresRouteImport.update({
  id: '/militares',
  path: '/militares',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/militares': typeof MilitaresRoute
  '/registros': typeof RegistrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/militares' | '/registros'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/militares' | '/registros'
  id: '__root__' | '/' | '/auth' | '/militares' | '/registros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MilitaresRoute: typeof MilitaresRoute
  RegistrosRoute: typeof RegistrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/militares': {
      id: '/militares'
      path: '/militares'
      fullPath: '/militares'
      preLoaderRoute: typeof MilitaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MilitaresRoute: MilitaresRoute,
  RegistrosRoute: RegistrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
